apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-logs
spec:
  template:
    spec:
      containers:
      - name: vector
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "2Gi"
            cpu: "200m"
        env:
        - name: VECTOR_LOG
          value: "DEBUG"
        - name: AWS_REGION
          value: "us-east-2"
        - name: AWS_DEFAULT_REGION
          value: "us-east-2"
        - name: S3_BUCKET_NAME
          value: "multi-tenant-logging-development-641875867446-us-east-2"
        - name: S3_WRITER_ROLE_ARN
          value: "arn:aws:iam::641875867446:role/multi-tenant-logging-development-central-s3-writer-role"
        - name: CLUSTER_ID
          value: "scuppett-oepz"