apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: default
type: Opaque
stringData:
  # MinIO default credentials for testing
  access-key: "minioadmin"
  secret-key: "minioadmin"